export enum EquipmentEvents {
  FETCH_STATUS_LOG_ENTRIES = 'fetch:statusLogEntries',
  FETCH_CATEGORIES = 'fetch:categories',
  FETCH_EQUIPMENT_RECORD = 'fetch:equipmentRecord',
  FETCH_EQUIPMENT = 'fetch:equipment',
  FETCH_EQUIPMENT_BUSINESSES = 'fetch:equipmentBusinesses',
  FETCH_EVENT_TYPES = 'fetch:eventTypes',
  FETCH_BUSINESSES = 'fetch:businesses',
  FETCH_WARRANTIES = 'fetch:warranties',
  FETCH_EVENT_TYPES_LOG = 'fetch:eventTypesLog',
  FETCH_EVENTS = 'fetch:events',
  FETCH_EQUIPMENT_EVENT_LOG = 'fetch:equipmentEventLog',
  FETCH_METERS = 'fetch:meters',
  FETCH_METER_READINGS = 'fetch:meterReadings',
  FETCH_METER_UNITS = 'fetch:meterUnits',
  FETCH_STATUSES = 'fetch:statuses',
  FETCH_FILTERS = 'fetch:filters',
  FETCH_WARRANTY_PROVIDERS = 'fetch:warrantyProviders',
  FETCH_PARTS_AND_BOM = 'fetch:partsAndBOM',
  FETCH_PARTS_LOG = 'fetch:partsLog',
  FETCH_SCHEDULED_MAINTENANCE = 'fetch:scheduledMaintenances',
  FETCH_WORK_ORDER = 'fetch:workOrders',
  UPDATE_FILTER = 'update:filter',
  DELETE_FILTER = 'delete:filter',
  CLEAR_SELECTED_EQUIPMENT = 'clear:selectedEquipment',
}
