export enum FeatureProperties {
  GENERATING_QRCODES = 'GENERATING_QRCODES',
  IMPORT_EQUIPMENT = 'IMPORT_EQUIPMENT',
  IMPORT_WARRANTIES = 'IMPORT_WARRANTIES',
  BULK_UPDATE_EQUIPMENT = 'BULK_UPDATE_EQUIPMENT',
  CREATE_SM_WIP = 'CREATE_SM_WIP',
  EVENTS_WIP = 'EVENTS_WIP',
}
